apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cp4ba-run
  namespace: default
spec:
  timeouts:
    pipeline: "2h30m00s"
    tasks: "2h29m59s"
  pipelineRef:
    name: cp4ba-deploy
  params:
    - name: CP4BA-VERSION
      value: "22.0.2"
    - name: namespace
      value: "cp4ba-starter"
  workspaces:
    - name: ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  podTemplate:
    securityContext:
      fsGroup: 65532