apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cp4ba-run
  namespace: default
spec:
  timeouts:
    pipeline: "9h30m00s"
    tasks: "8h59m59s"
    finally: "0h30m00s"
  pipelineRef:
    name: cp4ba-deploy
  params:
    - name: cp4ba-case
      value: "24.0.0-IF003"
    - name: namespace
      value: "cp4ba-starter"
    - name: mode
      value: "starter"
    - name: myAPIKey
      value: "myAPIKey"
    - name: projectId
      value: "00000000-1111-2222-3333-444444444444"
    - name: providerUrl
      value: "https://us-south.ml.cloud.ibm.com"
    - name: myUserId
      value: "malek.jabri@be.ibm.com"
  workspaces:
    - name: ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi