apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cp4ba-run
  namespace: default
spec:
  timeouts:
    pipeline: "9h00m00s"
    tasks: "8h29m59s"
    finally: "0h30m00s"
  pipelineRef:
    name: cp4ba-deploy
  params:
    - name: cp4ba-case
      value: "5.1.2"
    - name: namespace
      value: "cp4ba-starter"
  workspaces:
    - name: ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi